name: Update Repos' Environments

on:
  workflow_dispatch:    # Allows manual triggering of the workflow

jobs:
  terraform_apply:
    name: Apply Terraform
    runs-on: ubuntu-latest
    permissions: # https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.3  # Use the latest Terraform version or the version you need

      - name: Initialize Terraform
        run: terraform init

      - name: Download Plan Output
        uses: actions/download-artifact@v3
        with:
          name: tfplan-${{ github.sha }}
          path: tfplan-${{ github.sha }}

      - name: Apply Terraform
        run: terraform apply -auto-approve tfplan-${{ github.sha }}

    env:
      TF_VAR_github_owner: ${{ github.actor }}
      TF_VAR_github_token: ${{ secrets.GH_PAT }}
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_TOKEN }} # used as a bearer authorization token when the CLI makes service requests to the hostname app.terraform.io
